### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jackhu1990** [stm32duino/STM32FreeRTOS#15]
hello, i use vscode + platformio + arduino + stm32f103 to dev and i am a new fish.
i can add other libs like ArduinoJson by the platformio libraries tool, everthing is ok.
but when i add stm32duino/STM32FreeRTOS,  i get some error.
![image](https://user-images.githubusercontent.com/9961996/55805103-58448280-5b10-11e9-93df-1b3b3709fdc2.png)

i modify config_default.h `#define __CORTEX_M 0x03U`

i have no ways...

**Comment by fpistm** [comment]
This library is for "official" STM32 core not maple. That's why it misses several types.
