### ISSUE TITLE
Would this lib work with libopencm3 as well?

### ISSUE THREAD

**Issue by bjwschaap** [stm32duino/STM32FreeRTOS#20]
I currently have some projects set-up in PlatformIO, using libopencm3. I would like to add FreeRTOS using this library. However, right now it is defined only for framework "Arduino".

**Comment by fpistm** [comment]
Hi @bjwschaap 
This library is mainly for the STM32 core for Arduino that's why it was created to Arduino library format.
About using with PIO and libopencm3, I don't know as I'm not PIO user.
You should ask to PIO forum.
