### ISSUE TITLE
Missing include file for message_buffer.h

### ISSUE THREAD

**Issue by ramboerik** [stm32duino/STM32FreeRTOS#21]
Hi,

I'm trying to use FreeRTOS' message buffer implementation but there seems to be one file missing. All FreeRTOS' types have a include wrapper in ``src`` but the wrapper for ``message_buffer.h`` is missing. Could you add it 😃?

**Comment by fpistm** [comment]
Hi  @ramboerik 
do not hesitate to submit a PR :wink:

**Comment by ramboerik** [comment]
hehe okay, here it is #22
