### ISSUE TITLE
my task just run once

### ISSUE THREAD

**Issue by andhieSetyabudi** [stm32duino/STM32FreeRTOS#23]
Hello, i have a problem..
i use this library in platformio for stm32l476 - nucleo..
i create 2 task just like example shown in Analogread_digitalread.
but all task just run once...
please help me.

**Comment by ogatatsu** [comment]
hi.
in the `platformio.ini` file
`lib_archive = false`
Seems to need to be added

**Comment by andhieSetyabudi** [comment]
> hi.
> in the `platformio.ini` file
> `lib_archive = false`
> Seems to need to be added

hello @ogatatsu , thanks so much..
it seems run normally.. 
thanks for your advice...
