### ISSUE TITLE
Hardfault on CMSIS OS v2

### ISSUE THREAD

**Issue by danyhm** [stm32duino/STM32FreeRTOS#25]
Hello,

I installed the library via Arduino library manager and tried running the examples on an STM32 blue pill.

all examples except the ones in CMSIS-RTOSv2 run fine. if I try to run the examples in CMSIS-RTOSv2 the MCU enters a hardfault with 3 (or 4) blinks immediately.

I narrowed the problem down to be from the CMSIS-RTOSv2 configurations because whenever I enable configUSE_CMSIS_RTOS_V2 the hardfault happens otherwise it runs fine.

I hope it helps.

**Comment by fpistm** [comment]
Hi @danyhm,
I've tested and you're right, anyway as mentioned in the [README.md](https://github.com/stm32duino/STM32FreeRTOS#limitations):

> No CMSIS-RTOSv2 support provided. It is provided as example.

Do not hesitate to make a PR to fix this, it is a community organization and all contributions are welcome 😉

**Comment by danyhm** [comment]
@fpistm  I'll definitely look into it once my current project is done!

**Comment by fpistm** [comment]
@danyhm 
just for my interest which target you used ?

**Comment by danyhm** [comment]
I used the bluepill with CMSIS-RTOS-V1

**Comment by EasyNetDev** [comment]
Hi,

I've notice the same behavior with my BlackPill STM32F411CE. I tried CMSIS-RTOSv2 with a very-very simple task to blink the builtin LED at 1second and after uploading the software in the MCU it blinks fast 3 times and it stays on for a while then it repeats the sequence.
Is this CMSIS-RTOSv2 supported on F411CE or only on F411RE? They have same flash size, RAM size and speed.

Kind regards.

**Comment by fpistm** [comment]
Close as no update since a while and as:
> No CMSIS-RTOSv2 support provided. It is provided as example.
