### ISSUE TITLE
enabling LTO for compiler optimization causes compiler to fail with Error: offset out of range

### ISSUE THREAD

**Issue by danyhm** [stm32duino/STM32FreeRTOS#27]
Hello,
this bug has been already been mentioned in 
https://bugs.launchpad.net/gcc-arm-embedded/+bug/1763050

**Comment by fpistm** [comment]
Hi @danyhm 
I never advise to use LTO, I saw too much issue with it usage.
Anyway thanks for reporting.

**Comment by danyhm** [comment]
@fpistm you're welcome.

**Comment by danyhm** [comment]
@fpistm for whatever reason the pull merge does not show up in the library version 10.0.2 when updating from Arduino library manager. I tried deleting and reinstalling the library but the changes don't show up.

**Comment by fpistm** [comment]
This is not in the last release version. It is merged in the master that's all
