### ISSUE TITLE
fatal error: stm32_def.h: No such file or directory

### ISSUE THREAD

**Issue by heathkit** [stm32duino/STM32FreeRTOS#3]
Hi there! Really excited to use this library in PlatformIO. However, with a simple project I'm not able to build. Here's my platformio.ini

```
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
debug_tool = stlink-v2
build_flags = -std=gnu++11 -MMD -DCONFIG_MAPLE_MINI_NO_DISABLE_DEBUG=1 -DSERIAL_USB 
build_unflags = -lc -lstdc++ -lnosys

lib_deps =
  Nanopb
  PacketSerial
  STM32duino FreeRTOS
```

When I try to build, I get this error while building FreeRTOS

```
Compiling .pioenvs/bluepill_f103c8/lib823/STM32duino FreeRTOS_ID2093/FreeRTOS/Source/event_groups.o
In file included from .piolibdeps/STM32duino FreeRTOS_ID2093/src/FreeRTOS/Source/include/portable.h:94:0,
from .piolibdeps/STM32duino FreeRTOS_ID2093/src/FreeRTOS/Source/include/FreeRTOS.h:104,
from .piolibdeps/STM32duino FreeRTOS_ID2093/src/FreeRTOS.h:9,
from .piolibdeps/STM32duino FreeRTOS_ID2093/src/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.h:101,
from .piolibdeps/STM32duino FreeRTOS_ID2093/src/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c:100:
.piolibdeps/STM32duino FreeRTOS_ID2093/src/portmacro.h:9:23: fatal error: stm32_def.h: No such file or directory
```

**Comment by fpistm** [comment]
Hi,
unfortunately, this library is designed to be used with this core:
https://github.com/stm32duino/Arduino_Core_STM32
You use the one from @rogerclarkmelbourne:
https://github.com/rogerclarkmelbourne/Arduino_STM32
Which are not the same.
I know there is a request in platform.io community to support this core:
https://community.platformio.org/t/stm32-nucleo-discovery-boards-for-arduino/3027

Note that there is also a port of FreeRTOS for @rogerclarkmelbourne  core:
https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/FreeRTOS900

**Comment by rogerclarkmelbourne** [comment]
There is a several version of FreeRTOS bundled as a library in https://github.com/rogerclarkmelbourne/Arduino_STM32, so I"m not sure why @heathkit would try to use this library

See

https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/FreeRTOS900

https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/FreeRTOS821

https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/FreeRTOS

**Comment by fpistm** [comment]
@rogerclarkmelbourne probably because this one has just been referenced by Arduino in the Library manager. ;)

**Comment by heathkit** [comment]
It was recently added to PlatformIO: http://platformio.org/lib/show/2093/STM32duino%20FreeRTOS

If you start a new STM32 project on PlatformIO and search for a FreeRTOS library, this is what you find. Is there a missing dependency?

**Comment by rogerclarkmelbourne** [comment]
Umm

Platformio always throws up lots of problems :-(

The Platforino guys should really link to their primary sources and the forums for each one of them.

**Comment by fpistm** [comment]
I don't know how platform IO handle dependencies.
All libraries related to this github organization are for arch stm32.
Those for @rogerclarkmelbourne core (based on leaflabs) are for arch stm32f1 or stm32f4.
https://github.com/stm32duino/STM32FreeRTOS/blob/24cd55d0fbcf93ca742e6f6a0ece3a41e8c153b3/library.properties#L9

**Comment by fpistm** [comment]
@rogerclarkmelbourne it seems platform io automatically import new library published in Ardhuino library manager.

**Comment by rogerclarkmelbourne** [comment]
@fpistm 

This is a platformio issue, if they don't import the right libraries to match the core.

I've never been contacted by the Platformio team.
I don't support Platformio in my core as its too much work. (remember this is not my day job)
It says explicitly in my Readme.md that its for the Arduino IDE only.

**Comment by fpistm** [comment]
I know ;)
I've only answered to @heathkit  about why this lib do not work as it is not for the same core.
@heathkit I close this issue as unrelated to this library.

**Comment by fpistm** [comment]
In fact, there is at least an issue with the lib. It should not use internal core  header and use standard Arduino.h as entry point.

**Comment by mfatihkoc** [comment]
Hey, I have these error on my code, what to do? could you please help me?

BalancingWii:18:17: error: def.h: No such file or directory

compilation terminated

exit status 1
def.h: No such file or directory

**Comment by fpistm** [comment]
Hi @heathkit 
if you used PIO then you have to enter an issue on its related GitHub.
Moreover, just telling it doesn't compile is not enough.
Which IDE, core version, sketch example, all relevant and helpful info,...
