### ISSUE TITLE
Bug in heap_useNewlib.c

### ISSUE THREAD

**Issue by KiraVerSace** [stm32duino/STM32FreeRTOS#31]
https://github.com/stm32duino/STM32FreeRTOS/blob/master/portable/MemMang/heap_useNewlib.c

L56 
I think you should change the code to 
`#if (__NEWLIB__ >= 2) || (__NEWLIB_MINOR__ >= 5)`
cause the newlib has been update too many times .  I used 3.1.0

```
#ifndef _NEWLIB_VERSION_H__
#define _NEWLIB_VERSION_H__ 1

#define _NEWLIB_VERSION "3.1.0"
#define __NEWLIB__ 3
#define __NEWLIB_MINOR__ 1
#define __NEWLIB_PATCHLEVEL__ 0

#endif /* !_NEWLIB_VERSION_H__ */
```

**Comment by fpistm** [comment]
Hi @KiraVerSace 
this is not a bug just a warning.
