### ISSUE TITLE
compilation time is too long

### ISSUE THREAD

**Issue by Nanmei** [stm32duino/STM32FreeRTOS#36]
My arduino ide compilation time is too long, each compilation takes 8 minutes or more, is there any way to solve it? Thank you very much.

**Comment by fpistm** [comment]
Hi @Nanmei 
unfortunately, we can't do nothing to speed up. It is related to Arduino IDE on Windows.
On Linux the compilation is few seconds while on Windows it is several minutes.

**Comment by Nanmei** [comment]
Thanks.
