### ISSUE TITLE
xTaskCreateStatic was not declared

### ISSUE THREAD

**Issue by Nanmei** [stm32duino/STM32FreeRTOS#37]
I use xTaskCreateStatic create task ,the Compiler display “xTaskCreateStatic was not declared“,but xTaskCreate was correct.  

![C542609B-F370-4BAC-9EC3-813B1E2A0D7F](https://user-images.githubusercontent.com/80303463/111418123-11129380-8722-11eb-917b-003fbe2c3771.png)

**Comment by fpistm** [comment]
You have to set the `configSUPPORT_STATIC_ALLOCATION` to 1.
https://www.freertos.org/xTaskCreateStatic.html

Anyway we do not support nor test all the config. You will be on your own for this.

**Comment by Nanmei** [comment]
Thanks,
