### ISSUE TITLE
Custom STM32FreeRTOSConfig.h usage with platform io

### ISSUE THREAD

**Issue by Magamanny** [stm32duino/STM32FreeRTOS#45]
Hello,
I am using platform io with STM32FreeRTOS.
I am trying to modify some setting of the FreeRTOS, but the setting don't take effect and it always uses the STM32FreeRTOSConfig_Default(I think). 
I have create a  file named 'STM32FreeRTOSConfig.h' in my include directory and copied the setting form STM32FreeRTOSConfig_Default, and modified it.
I am using 'stm32duino/STM32duino FreeRTOS @ ^10.2.1' to add the library.

**Comment by fpistm** [comment]
Hi @Magamanny 
We do not support PIO only Arduino IDE and don't know how PIO manage the build probably a config to add in the json.
In Arduino the configuration works as expected so you should ask to PIO how to do this.
