### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by jfitter** [stm32duino/STM32FreeRTOS#5]
Nothing I can do will make this compile.
`Compiling debug version of 'frBlink' for 'Maple Mini'
 
The STM32duino_FreeRTOS library encountered an unknown path resolve error.In file included from D*: Users\jfitter\Documents\Arduino\libraries\STM32duino_FreeRTOS\src/FreeRTOS/Source/include/portable.h:94:0
FreeRTOS.h:104: from
FreeRTOS.h:9: from
cmsis_os.h:101: from
cmsis_os.c:100: from
 
portmacro.h: 12:20: error: no "__CORTEX_M" definition
   #pragma GCC error  "no \"__CORTEX_M\" definition"
 
cmsis_os.c: 122:25: fatal error: cmsis_gcc.h: No such file or directory
   #include "cmsis_gcc.h"
   compilation terminated
Debug build failed for project 'frBlink'`

**Comment by fpistm** [comment]
This library is mainly for this core: https://github.com/stm32duino/Arduino_Core_STM32
It uses the cmsis which define the __CORTEX_M macro. I think you

**Comment by fpistm** [comment]
I think you use the core from Roger. Arduino_stm32 which do notre use the cmsis. So you have to define yourself this macro. I know There is also a freertos library provided with Roger core.

**Comment by jfitter** [comment]
Yes, you are right. I am using Roger's core. I did define the macro but that led to other problems. I will try to find Roger's FreeRtos port. Thankyou.
I would like to use Arduino_Core_STM32 but it appears to not support the Maple and Blue Pill boards.

**Comment by fpistm** [comment]
PR to support them will Come soon. For Roger's core: https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/FreeRTOS900
