### ISSUE TITLE
Why the freertos version is so old？

### ISSUE THREAD

**Issue by zouzhe1** [stm32duino/STM32FreeRTOS#53]
new version is 10.4.6（21.11.13），
our current version is 10.3.1（20.1.19）.。。。。。
2.5 years ago。。。。

**Comment by fpistm** [comment]
As explained in the README.md:

> These are the same provided with the [STM32Cube MCU Packages](http://www.st.com/en/embedded-software/stm32cube-mcu-packages.html). Or thanks to [STMicroelectronics GitHub organization](https://github.com/STMicroelectronics): [stm32_mw_freertos](https://github.com/STMicroelectronics/stm32_mw_freertos).

So latest one provided by the STMicroelectronics repo is https://github.com/STMicroelectronics/stm32_mw_freertos/releases/tag/v10.3.1.
