### ISSUE TITLE
Can not use HID bootloader while using STM32FreeRTOS

### ISSUE THREAD

**Issue by PadmaIoT** [stm32duino/STM32FreeRTOS#55]
Hi,
I was using the [HID bootloader for USB](https://github.com/Serasidis/STM32_HID_Bootloader/releases) for Arduino IDE for several months. But when I inserted the FreeRTOS I lost the com port for the blue pill. And look like the program does not work, though the program is uploaded. I mean I tried to use pc13 to blink1 and  PA4 to blink2 program (blink 1 & 2 are for different time delays). How can I solve this?

**Comment by PadmaIoT** [comment]
Hi,
I am not able to get any answers from the developer until now. Please would you please see the issue?

**Comment by fpistm** [comment]
Hi @PadmaIoT 

Which version of the core you used ?
You should try the 2.3.0, we fixed the system init to ensure all configuration is ok after bootloader exit (jump to application).
If it does not work, I have no more idea.

**Comment by PadmaIoT** [comment]
I am using 2.3.0 core.

**Comment by PadmaIoT** [comment]
Do you have any support for STM32F103C8T6 chip? Bcz I did not find one. @fpistm

**Comment by fpistm** [comment]
Yes it is available:
https://github.com/stm32duino/Arduino_Core_STM32/blob/3ef013a908215586b4b738772ba25be588920fdf/boards.txt#L1517-L1523

**Comment by fpistm** [comment]
Tested and not reproduced.
