### ISSUE TITLE
STM32 Free RTOS problem with the STM32Ethernet library

### ISSUE THREAD

**Issue by mattia424** [stm32duino/STM32FreeRTOS#56]
I tried compiling this example (https://github.com/stm32duino/STM32Ethernet/commit/7669880d8f1347b45f4bc2749ce9ef3eaf2b40ba) for my STM32F429ZI board but when I remove and replace the ethernet cable the program crashes. Is there any way to fix this?

**Comment by fpistm** [comment]
Hi @mattia424 
please avoid to open several issue for the same purpose.
I close this one as the second seems more detailed.
https://github.com/stm32duino/STM32Ethernet/issues/65
