### ISSUE TITLE
Updated to V10?

### ISSUE THREAD

**Issue by davidanger** [stm32duino/STM32FreeRTOS#6]
Is have plan to updated to FreeRTOS v10?

**Comment by rogerclarkmelbourne** [comment]
Its a user contributed project.

You'd need to look at the commit history, see who sent the last PR for FreeRTOS and then contact them.

**Comment by fpistm** [comment]
Hi,
yes it's planned to update this library to v10 when I've got some time.
Anyway if someone want to contribute, he can do a PR for that.

**Comment by rogerclarkmelbourne** [comment]
Sorry. Frederic

I thought this was a reference to the version in my repo.

Ignore my comment.

**Comment by fpistm** [comment]
No worries @rogerclarkmelbourne  ;)
