### ISSUE TITLE
USB Serial is not working with STM32FreeRTOS in STM32 black pill

### ISSUE THREAD

**Issue by arunk98475** [stm32duino/STM32FreeRTOS#70]
In my STM32 project i want to use both FreeRTOS and Serial communication . But after include FreeRTOS dependency , the serial connection is not working. I am working in PlatformIO 
See the below is my test code

```
//#include <STM32FreeRTOS.h>
#include <Arduino.h>
void setup() {

  Serial.begin(9600);
  Serial.println("Serial Started...");
}
void loop() {
  Serial.println("Hello world..");
  delay(1000);
}
```

And PlatformIO configuration is below

```
[env:STM32]
platform = ststm32
board = blackpill_f411ce
framework = arduino
upload_protocol = dfu
monitor_speed = 115200
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
build_src_filter=+<*> -<.git/> -<.svn/> -<doc/>
lib_deps=https://github.com/stm32duino/STM32FreeRTOS.git
```

But I found that COM port is detecting in the windows but serial monitor is not able to connect to the COM port . If i comment out the line '**lib_deps=https://github.com/stm32duino/STM32FreeRTOS.git**'  then serial starts working

**Comment by fpistm** [comment]
https://github.com/stm32duino/STM32FreeRTOS/issues/58#issuecomment-1482421973
