### ISSUE TITLE
Memory manager to safely use malloc() from other libraries

### ISSUE THREAD

**Issue by ppescher** [stm32duino/STM32FreeRTOS#9]
The current options in the `portable/MemMang` directory cannot provide thread safety for those Arduino libraries that directly call `malloc()` family of functions (e.g. STM32SD, String).

I have ported some code here: https://github.com/RoboTech-srl/STM32FreeRTOS/commit/897009a2ad988ad7fdaec36c1008f335349d6803

Before making a PR, I was wondering if `configMEMMANG_HEAP_NB == -1` was a good choice. I thought the number of heap implementations might grow in future versions, so I went negative. What do you think @fpistm ?

I also think that the default `_sbrk()` provided by the core must be defined as a "weak" symbol for this to work. See https://github.com/RoboTech-srl/opentracker-stm32-core/commit/169ced0703e55bd6827d0406fdd768c6617c7a9c

**Comment by fpistm** [comment]
Thanks @ppescher 
I will checkout this tomorrow, I'm currently working on an issue around malloc #8.
As I pointed in the thread and during my investigation I've planned to give a try to this heap_useNewlib.c which is provided in the link I've post to @rayozzie.
Nice to have your proposal.
